.TH <template>: "3" "June 2017" "<template>: <template> v0.1" "Library Calls"

.SH "NAME"
<template> - <template>

.SH "SYNOPSIS"
.sp
.nf
\fI<template>\fR [\-hv] [\-o\fI<output.c>\fR]
.fi

.SH "DESCRIPTION"
.sp
Dynamically load non-shared ELF executables with dlopen().

.SH "USAGE"
.sp
<template>

.SH "AUTHOR"
.sp
Joey Pabalinas <joeypabalinas@gmail.com>

.SH "NOTES"
.sp
https://github.com/alyptik/libdilf
